In [10]:
import numpy as np
import os
import pandas as pd
from tqdm.notebook import tqdm
import copy

In [11]:
class Node:
    def __init__(self, value):
        self.value = value
        self.neighbors = set()
        self.parent = None
        self.level = None
        self.visited = False
    
    #Retorna o índice do vértice quando for chamado
    def __repr__(self): 
        return str(self.value)
    
    #Adiciona um vértice adjacente
    def add_neighbor(self, w):
        self.neighbors.add(w)
    
    #Retorna o índice do vértice
    def get_value(self):
        return self.value
    
    #Retorna os vértices adjacentes
    def get_neighbors(self):
#         return self.neighbors
        return sorted(self.neighbors, key=lambda x: x.value)

In [12]:
a = [1, 2]

In [13]:
del a[0]

In [14]:
a

[2]

In [5]:
class Graph:
    
    def __init__(self, n):
        self.n_nodes = n
        self.matrix = np.zeros((n, n), dtype="object")
        self.nodes = np.empty(n, dtype="object")
        
        pbar = tqdm(range(n), desc="Adding edges...")
        
        for index in tqdm(range(n)):
            self.add_node(index + 1)
       

    def add_node(self, value):
        index = value - 1
        self.nodes[index] = Node(value)
    
    def add_edge(self, v_value, w_value):
        v_index = v_value - 1
        w_index = w_value - 1
        
        if v_value == w_value:
            self.matrix[v_index, v_index] = 2
            self.nodes[v_index].add_neighbor(self.nodes[v_index])
            
        else:
            self.matrix[v_index, w_index] = 1
            self.matrix[w_index, v_index] = 1
            self.nodes[v_index].add_neighbor(self.nodes[w_index])
            self.nodes[w_index].add_neighbor(self.nodes[v_index])
    
    def get_node(self, value):
        index = value - 1
        return self.nodes[index]
    
    def get_nodes(self):
        return self.nodes
    
    def get_node_edges(self):
        return {node.value:node.get_neighbors() for node in self.nodes}
    
    def get_matrix(self):
        return self.matrix
    
    def get_matrix_beautiful(self):
        return pd.DataFrame(self.matrix, columns=np.arange(1, self.n_nodes+1), index=np.arange(1, self.n_nodes+1))
    
    def get_lists(self):
        return [node.get_neighbors() for node in self.nodes]

In [6]:
def open_graph_txt(filename, extra=False):
    with open(filename, "r") as f:
        lines = f.read().split("\n")
        n_nodes = int(lines[0])
        edges = [tuple(map(lambda i: int(i), line.split(" "))) for line in lines[1:-1]]
    
    graph = Graph(n_nodes)
    for v, w in edges:
        graph.add_edge(v, w)
    
    if extra:
        return graph, n_nodes, edges
    
    return graph

In [7]:
folder = "inputs"
filename = "grafo_1.txt"

path = os.path.join(folder, filename)

In [8]:
graph = open_graph_txt(path)

Adding edges...:   0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

In [9]:
graph.get_node_edges()

{1: {1, 16, 22, 3, 31, 45, 46, 52, 82, 83, 84, 93},
 2: {11, 14, 19, 2, 33, 37, 38, 49, 5, 99},
 3: {1, 14, 36, 39, 52, 76, 80, 83, 85, 94, 95},
 4: {15, 24, 26, 39, 7, 71, 76, 84, 88, 92, 95, 98, 99},
 5: {14, 19, 2, 23, 55, 59, 62, 65, 7, 91, 94, 95, 98},
 6: {100, 15, 22, 48, 50, 59, 62, 71, 79, 83, 91},
 7: {13, 27, 33, 36, 4, 43, 5, 52, 56, 74, 84, 87, 90},
 8: {34, 40, 49, 50, 57, 58, 60, 65, 89},
 9: {10, 11, 15, 16, 21, 24, 46, 60, 65, 75, 89, 90, 99},
 10: {20, 53, 72, 73, 82, 83, 9, 90, 97},
 11: {14, 2, 22, 23, 25, 46, 57, 80, 9, 97},
 12: {13, 16, 45, 51, 55, 61, 70, 73, 76, 80, 85},
 13: {12, 40, 48, 49, 58, 59, 7, 81, 99},
 14: {11, 16, 2, 3, 32, 45, 5, 55, 64, 83},
 15: {100, 26, 34, 4, 56, 6, 65, 9, 93, 94, 98},
 16: {1, 12, 14, 19, 25, 51, 60, 62, 89, 9, 93, 94},
 17: {23, 27, 30, 34, 42, 61, 64, 72, 81, 82, 83, 89, 93, 94},
 18: {19, 28, 38, 44, 67, 69, 71, 72, 78, 86, 99},
 19: {100, 16, 18, 2, 27, 34, 35, 5, 53, 69, 70, 86, 97},
 20: {10, 22, 28, 31, 32, 42, 55, 74,

In [8]:
graph.get_lists()

[[1, 3, 16, 22, 31, 45, 46, 52, 82, 83, 84, 93],
 [2, 5, 11, 14, 19, 33, 37, 38, 49, 99],
 [1, 14, 36, 39, 52, 76, 80, 83, 85, 94, 95],
 [7, 15, 24, 26, 39, 71, 76, 84, 88, 92, 95, 98, 99],
 [2, 7, 14, 19, 23, 55, 59, 62, 65, 91, 94, 95, 98],
 [15, 22, 48, 50, 59, 62, 71, 79, 83, 91, 100],
 [4, 5, 13, 27, 33, 36, 43, 52, 56, 74, 84, 87, 90],
 [34, 40, 49, 50, 57, 58, 60, 65, 89],
 [10, 11, 15, 16, 21, 24, 46, 60, 65, 75, 89, 90, 99],
 [9, 20, 53, 72, 73, 82, 83, 90, 97],
 [2, 9, 14, 22, 23, 25, 46, 57, 80, 97],
 [13, 16, 45, 51, 55, 61, 70, 73, 76, 80, 85],
 [7, 12, 40, 48, 49, 58, 59, 81, 99],
 [2, 3, 5, 11, 16, 32, 45, 55, 64, 83],
 [4, 6, 9, 26, 34, 56, 65, 93, 94, 98, 100],
 [1, 9, 12, 14, 19, 25, 51, 60, 62, 89, 93, 94],
 [23, 27, 30, 34, 42, 61, 64, 72, 81, 82, 83, 89, 93, 94],
 [19, 28, 38, 44, 67, 69, 71, 72, 78, 86, 99],
 [2, 5, 16, 18, 27, 34, 35, 53, 69, 70, 86, 97, 100],
 [10, 22, 28, 31, 32, 42, 55, 74, 92, 96],
 [9, 29, 44, 50, 52, 58, 72, 82, 84, 94, 100],
 [1, 6, 11, 20

In [9]:
graph.get_matrix()

array([[2, 0, 1, ..., 0, 0, 0],
       [0, 2, 0, ..., 0, 1, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 1, 0]], dtype=object)

In [10]:
graph.get_matrix_beautiful()

1   2   3   4   5   6   7   8   9   10   ... 91  92  93  94  95  96  97   \
1     2   0   1   0   0   0   0   0   0   0  ...   0   0   1   0   0   0   0   
2     0   2   0   0   1   0   0   0   0   0  ...   0   0   0   0   0   0   0   
3     1   0   0   0   0   0   0   0   0   0  ...   0   0   0   1   1   0   0   
4     0   0   0   0   0   0   1   0   0   0  ...   0   1   0   0   1   0   0   
5     0   1   0   0   0   0   1   0   0   0  ...   1   0   0   1   1   0   0   
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
96    0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
97    0   0   0   0   0   0   0   0   0   1  ...   0   0   0   0   0   0   0   
98    0   0   0   1   1   0   0   0   0   0  ...   0   0   0   0   0   0   0   
99    0   1   0   1   0   0   0   0   1   0  ...   0   0   0   0   0   0   0   
100   0   0   0   0   0   1   0   0   0   0  ...   0   0   0   0   0   1   1   

    98  99  100  
1     0   0   0  
2     0   1   0  
3     0   0   0  
4     1   1   0  
5     1   0   0  
..   ..  ..  ..  
96    0   0   1  
97    0   0   1  
98    0   0   0  
99    0   0   1  
100   0   1   0  

[100 rows x 100 columns]

In [11]:
def graph_statistics(graph):
    print("Número de vértices:", graph.n_nodes)
    print("Número de arestas:", graph.get_matrix().sum()/2)
    print("Grau mínimo:", graph.get_matrix().sum(axis=0).min())
    print("Grau máximo:", graph.get_matrix().sum(axis=0).max())
    print("Grau médio:", graph.get_matrix().sum(axis=0).mean())
    print("Mediana do Grau:", np.median(graph.get_matrix().sum(axis=0)))

In [12]:
graph_statistics(graph)

Número de vértices: 100
Número de arestas: 569.0
Grau mínimo: 5
Grau máximo: 16
Grau médio: 11.38
Mediana do Grau: 11.0


In [13]:
class Stack:
    
    def __init__(self, size):
        self.size = size
        self.top = -1
        
        self.values = np.empty(self.size, dtype="object")
    
    def is_full(self):
        return (self.top == self.size - 1)
    
    def is_empty(self):
        return (self.top == -1)
    
    def stack_up(self, node):
        if self.is_full():
            raise OverflowError("Stack is full.")
        else:
            self.top += 1
            self.values[self.top] = node
    
    def unstack(self):
        if self.is_empty():
            raise ValueError("Stack is empty.")
        else:
            temp = self.values[self.top]
            self.top -= 1
            return temp
    
    def get_top(self):
        if self.top != -1:
            return self.values[self.top]
        else:
            return -1
        

In [14]:
class DFS:
    def __init__(self, graph, root):
        self.graph = copy.deepcopy(graph)
        self.root = self.graph.nodes[root-1]
        self.root.level = 0
        self.root.visited = True
        self.stack = Stack(size=graph.n_nodes)
        self.stack.stack_up(self.root)
    
    def search(self):
        top = self.stack.get_top()
        for neighbor in top.get_neighbors():
            if neighbor.value == top.value:
                continue
            
            if not neighbor.visited:
                neighbor.parent = top
                neighbor.level = top.level + 1
                neighbor.visited = True
                self.stack.stack_up(neighbor)
                self.search()
        self.stack.unstack()

In [15]:
dfs = DFS(graph, 1)

In [16]:
dfs.search()

In [16]:
a = np.array([1])

In [17]:
np.append(np.array([1]), 2)

array([1, 2])

In [18]:
a

array([1])

In [20]:
class Queue:
    def __init__(self, size):
        self.size = size
        self.top = -1
        
        self.queue = np.empty(self.size, dtype="object")
    
    def is_full(self):
        return (self.top == self.size - 1)
    
    def is_empty(self):
        return (self.top == -1)
    
    def add(self, node):
        if self.is_full and not self.is_empty:
            raise OverflowError("Queue is full.")
        self.top += 1
        self.queue[self.top] = node

    def next(self):
        if self.is_empty():
            raise ValueError("Queue is empty.")
        first = self.queue[0]
        self.queue = self.queue[1:]
        self.top -= 1
        np.append(self.queue, None)
        return first


    def get(self):
        return self.queue

In [18]:
class BFS:
    def __init__(self, graph, root):
        self.graph = copy.deepcopy(graph)
        self.root = self.graph.nodes[root-1]
        self.root.level = 0
        self.root.visited = True
        self.queue = Queue(size=graph.n_nodes)
        self.queue.add(self.root)
    
    def search(self):
        first = self.queue.next()
        for neighbor in first.get_neighbors():
            if first == neighbor:
                continue
            if not neighbor.visited:
                neighbor.visited = True
                neighbor.parent = first
                neighbor.level = first.level + 1
                self.queue.add(neighbor)
        
        if not self.queue.is_empty():
            self.search()

In [19]:
bfs = BFS(graph, 1)

In [20]:
bfs.search()

In [21]:
def write_parent_level_txt(filename, graph):
    with open(filename, "w") as f:
        for node in graph.nodes:
            f.write(f"Node: {node.value} -- Parent: {node.parent} -- Level: {node.level}\n")

In [22]:
filename = "outputs/dfs_tree.txt"
write_parent_level_txt(filename, dfs.graph)

In [23]:
filename = "outputs/bfs_tree.txt"
write_parent_level_txt(filename, bfs.graph)

In [28]:
class MinimumPath:
    
    def __init__(self, graph):
        self.graph = graph
        self.matrix = np.full((graph.n_nodes, graph.n_nodes), fill_value=None)
        self.run()
    
    def run(self):
        for node in self.graph.nodes:
            bfs = BFS(self.graph, node.value)
            bfs.search()
            for bfs_node in bfs.graph.nodes:
                self.matrix[node.value-1, bfs_node.value-1] = bfs_node.level
    
    def get_distance(self, u_value, v_value):
        return self.matrix[u_value-1, v_value-1]
    
    def get_diameter(self):
        return np.max(self.matrix)
    
    def get_matrix(self):
        return self.matrix
    
    def get_matrix_beautiful(self):
        return pd.DataFrame(self.matrix, columns=np.arange(1, self.graph.n_nodes+1), index=np.arange(1, self.graph.n_nodes+1))
    

In [29]:
minpath = MinimumPath(graph)

In [30]:
minpath.get_matrix()

array([[0, 3, 1, ..., 3, 3, 2],
       [3, 0, 2, ..., 2, 1, 2],
       [1, 2, 0, ..., 3, 3, 2],
       ...,
       [3, 2, 3, ..., 0, 2, 2],
       [3, 1, 3, ..., 2, 0, 1],
       [2, 2, 2, ..., 2, 1, 0]], dtype=object)

In [32]:
minpath.get_distance(1, 3)

1

In [33]:
minpath.get_diameter()

3

In [ ]:
#Componente conexa
#Verifica quem ainda não foi visitado, e roda a BFS no primeiro que não foi visitado
list(filter(lambda x: not x.visited, bfs.graph.nodes))

In [ ]:
from pyvis.network import Network

net = Network(notebook=True)

for node in graph.nodes:
    net.add_node(node.value, label=node.value)
    
for node in graph.nodes:
    for neighbor in node.neighbors:
        net.add_edge(node.value, neighbor.value)

net.show("graph.html")